"""add AI summary and ML acknowledgment columns

Revision ID: 0746ffb0c1c4
Revises: b8ccc064b16a
Create Date: 2026-08-25 22:12:35.741386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0746ffb0c1c4'
down_revision = 'b8ccc064b16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_acknowledged', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ml_acknowledged', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('ml_acknowledged')

    with op.batch_alter_table('ai_summaries', schema=None) as batch_op:
        batch_op.drop_column('is_acknowledged')

    # ### end Alembic commands ###
