"""add patient_id to audit_logs

Revision ID: b8ccc064b16a
Revises: 6c7d5e3b7a3d
Create Date: 2026-08-25 22:04:36.337165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ccc064b16a'
down_revision = '6c7d5e3b7a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_audit_logs_patient_id', 'patients', ['patient_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_logs_patient_id', type_='foreignkey')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
